In [1]:
import pandas as pd
filePath = "C:/Users/danna/Documents/GitHub/WBBTournamentPredictions/MachineLearning/LearningData/learningData3.csv"
df = pd.read_csv(filePath)
df.drop(["Unnamed: 0"], axis=1, inplace=True)
df

,TEAM,FG,FGA,2P,2PA,3P,3PA,FT,FTA,ORB,...,AST_MAX_OPP,STL_MAX_OPP,BLK_MAX_OPP,TOV_MAX_OPP,PF_MAX_OPP,PTS_MAX_OPP,FT/FGA_MAX_OPP,AST/TOV_MAX_OPP,WIN,GAME_ID
0,Austin Peay,16,53,13,39,3,14,7,9,8,...,4,2,2,4,5,18,0.571429,2.000000,False,0
1,Tennessee,31,67,26,48,5,19,8,13,21,...,1,1,1,7,4,21,0.222222,0.333333,True,0
2,Baylor,17,45,16,38,1,7,15,20,5,...,4,3,2,2,4,34,0.625000,2.000000,False,1
3,Connecticut,28,67,25,50,3,17,11,19,12,...,4,1,5,5,5,14,0.400000,1.500000,True,1
4,Baylor,18,53,16,41,2,12,13,20,8,...,2,4,1,4,5,16,0.388889,1.000000,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
947,Connecticut,27,58,23,43,4,15,11,17,8,...,3,2,3,3,4,16,0.375000,3.000000,True,473
948,UCLA,29,80,22,56,7,24,20,21,25,...,3,3,6,2,4,23,0.300000,1.500000,True,474
949,Maryland,32,68,31,55,1,13,15,25,17,...,5,2,1,5,3,30,0.625000,2.000000,False,474
950,Wright State,24,80,16,50,8,30,5,7,17,...,7,1,1,3,3,27,1.750000,3.500000,False,475
951,Texas A&M,25,56,17,39,8,17,26,35,11,...,3,1,1,4,5,12,0.666667,0.500000,True,475

In [14]:
dfClean = df.drop(["TEAM", "TEAM_OPP"], axis=1)
dfClean

,FG,FGA,2P,2PA,3P,3PA,FT,FTA,ORB,DRB,...,AST_MAX_OPP,STL_MAX_OPP,BLK_MAX_OPP,TOV_MAX_OPP,PF_MAX_OPP,PTS_MAX_OPP,FT/FGA_MAX_OPP,AST/TOV_MAX_OPP,WIN,GAME_ID
0,16,53,13,39,3,14,7,9,8,12,...,4,2,2,4,5,18,0.571429,2.000000,False,0
1,31,67,26,48,5,19,8,13,21,25,...,1,1,1,7,4,21,0.222222,0.333333,True,0
2,17,45,16,38,1,7,15,20,5,23,...,4,3,2,2,4,34,0.625000,2.000000,False,1
3,28,67,25,50,3,17,11,19,12,23,...,4,1,5,5,5,14,0.400000,1.500000,True,1
4,18,53,16,41,2,12,13,20,8,28,...,2,4,1,4,5,16,0.388889,1.000000,True,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
947,27,58,23,43,4,15,11,17,8,24,...,3,2,3,3,4,16,0.375000,3.000000,True,473
948,29,80,22,56,7,24,20,21,25,19,...,3,3,6,2,4,23,0.300000,1.500000,True,474
949,32,68,31,55,1,13,15,25,17,21,...,5,2,1,5,3,30,0.625000,2.000000,False,474
950,24,80,16,50,8,30,5,7,17,21,...,7,1,1,3,3,27,1.750000,3.500000,False,475
951,25,56,17,39,8,17,26,35,11,28,...,3,1,1,4,5,12,0.666667,0.500000,True,475

In [15]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

X = dfClean.drop(['WIN'], axis=1)
y = dfClean['WIN']

Xtrain, Xtest, yTrain, yTest = train_test_split(X, y, test_size=0.33, random_state=42)

In [18]:
Xtrain, yTrain

(     FG  FGA  2P  2PA  3P  3PA  FT  FTA  ORB  DRB  ...  DRB_MAX_OPP  \
 274  25   58  21   41   4   17  11   17   10   26  ...            8
 850  18   56  16   46   2   10   7   10   10   15  ...            6
 69   25   59  22   46   3   13  17   28   10   29  ...            5
 291  20   61  19   42   1   19   8    9   12   25  ...            8
 131  27   66  24   54   3   12  18   21   12   27  ...            6
 ..   ..  ...  ..  ...  ..  ...  ..  ...  ...  ...  ...          ...
 106  18   68  10   46   8   22   3    4   13   32  ...            9
 270  26   70  16   51  10   19   6    9   18   18  ...            7
 860  28   65  16   39  12   26   8   11    9   19  ...            4
 435  21   54  19   46   2    8  27   33   11   26  ...            7
 102  15   65  10   39   5   26   4    7   11   10  ...           10

      AST_MAX_OPP  STL_MAX_OPP  BLK_MAX_OPP  TOV_MAX_OPP  PF_MAX_OPP  \
 274            2            2            2            3           5
 850            5            1            2            4           4
 69             1            2            3            4           4
 291            5            2            2            6           4
 131           11            2            0            4           2
 ..           ...          ...          ...          ...         ...
 106            3            1            6            3           3
 270            3            2            6            3           2
 860            4            2            3            4           5
 435            4            3            1            4           4
 102            8            5            3            4           2

      PTS_MAX_OPP  FT/FGA_MAX_OPP  AST/TOV_MAX_OPP  GAME_ID
 274           20        0.500000         1.000000      137
 850           20        1.000000         5.000000      425
 69             8        1.000000         0.333333       34
 291           20        0.375000         1.000000      145
 131           18        0.000000         2.750000       65
 ..           ...             ...              ...      ...
 106           23        1.000000         1.000000       53
 270           35        0.571429         3.000000      135
 860           21        1.000000         4.000000      430
 435           24        1.000000         4.000000      217
 102           22        1.400000         2.666667       51

 [637 rows x 74 columns],
 274     True
 850    False
 69      True
 291    False
 131     True
        ...
 106    False
 270    False
 860    False
 435     True
 102    False
 Name: WIN, Length: 637, dtype: bool)

In [19]:
#ML frameworks
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB

modelPipe = []
modelPipe.append(LogisticRegression(solver='liblinear'))
modelPipe.append(SVC())
modelPipe.append(KNeighborsClassifier())
modelPipe.append(DecisionTreeClassifier())
modelPipe.append(RandomForestClassifier())
modelPipe.append(GaussianNB())

In [20]:
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

modelList = ['LogisticRegression', 'SVM', 'KNN', 'DecisionTree', 'RandomForest', 'NaiveBayes']
accList = []
aucList = []
cmList = []

for model in modelPipe:
    model.fit(Xtrain, yTrain)
    yPred = model.predict(Xtest)
    accList.append(metrics.accuracy_score(yTest, yPred))
    fpr, tpr, _thresholds = metrics.roc_curve(yTest, yPred)
    aucList.append(round(metrics.auc(fpr, tpr), 2))
    cmList.append(confusion_matrix(yTest, yPred))

C:\Users\danna\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [ ]:
fig = plt.